### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by mjr711** [polymorpher/one-wallet#1]
Hey there, I am looking to help test the wallet via android. If I could be of service please let me know. Thank you.

**Comment by polymorpher** [comment]
Thanks. Not ready yet. Apps will come out later.

**Comment by mjr711** [comment]
> 
> 
> Thanks. Not ready yet. Apps will come out later.

My apologies. I came here from the AMA on Harmony that was done yesterday and there may have been some miscommunication. That is how I found out about this. Apologies.

**Comment by polymorpher** [comment]
I am going to close this off for now. When the wallet is ready, I will reopen this and follow up.
