### ISSUE TITLE
1wallet not ok

### ISSUE THREAD

**Issue by saigoncoin** [polymorpher/one-wallet#105]
I can't paste an address here, it's fixed and nothing can be don
![1wallet](https://user-images.githubusercontent.com/31839061/131810814-bb6cd912-d143-417d-b698-43f8612fbcbf.PNG)
e.

**Comment by saigoncoin** [comment]
I can't paste an address here, it's fixed and nothing can be done.

**Comment by polymorpher** [comment]
Use control+v / command+v to paste for now. We will look into why right-click paste option is missing and fix it shortly

**Comment by polymorpher** [comment]
Fixed by https://github.com/polymorpher/one-wallet/pull/106
