### ISSUE TITLE
Wallet restore

### ISSUE THREAD

**Issue by L3onidass** [polymorpher/one-wallet#123]
I can't restore my wallet which I created few minutes ago and sent funds. Always when I enter my one wallet￼ address it's telling me that it is a smart contract￼ but not a wallet address. Is it possible to return the funds￼ beck to sender?

TxID
0x8229a45c66552bb1d993860bf879afda354fd2298b42c254129cab83861963f2

**Comment by polymorpher** [comment]
What's the 1wallet address you are entering? I tried using the To address provided in your txId, but it is showing an unidentifiable smart contract (e.g. Solidity version 0.7.4 - whereas 1wallet is always compiled with 0.8.4, and Creator is 0x4f9b1def3a0f6747bf8c870a27d3decdf029100e, whereas 1wallet should be created by 0xc8cd0c9ca68b853f73917c36e9276770a8d8e4e0)

**Comment by L3onidass** [comment]
> What's the 1wallet address you are entering? I tried using the To address provided in your txId, but it is showing an unidentifiable smart contract (e.g. Solidity version 0.7.4 - whereas 1wallet is always compiled with 0.8.4, and Creator is 0x4f9b1def3a0f6747bf8c870a27d3decdf029100e, whereas 1wallet should be created by 0xc8cd0c9ca68b853f73917c36e9276770a8d8e4e0)

My one wallet address one1qtev73wafwkt5zga0pgzmw3m9ap354xnf4qlmg

I don't know what cause differences with address or versions. I just reacted on tweet ![image](https://user-images.githubusercontent.com/90371307/132630723-7d6f1c32-c4de-4225-b9be-b1421a8666c7.png)
So I clicked on the link, created a new wallet and follow the steps. 

1) Scan QR code 
2) Enter a code from authenticator 
3) Send funds to pay gas fees

Did I do something wrong￼?

**Comment by polymorpher** [comment]
`one1qtev73wafwkt5zga0pgzmw3m9ap354xnf4qlmg` is `0x02f2cf45dd4bacba091d78502dba3b2f431a54d3`, which is not 1wallet. Nothing in 1wallet requires you to send funds to pay gas fees. Are you sure you were at the correct link?

**Comment by L3onidass** [comment]
Yes, I am sure you can try it. It's the same link which I posted on the picture￼. Honestly I was confused it's a first time when someone needed funds to pay gas fees for creating a new wallet. So it looks like a scam￼, luckily it was only 33dollars. But if you click on transaction ID there is some kind of error maybe is a way or chance to send funds back to sender￼￼.

https://1wallet.crazy.one/create

**Comment by polymorpher** [comment]
When a transaction is shown as "reverted", any funds sent would be automatically reverted back to the sender. I don't see anywhere in the link that asks you to send funds to pay gas fees. Can you take a screenshot of that portion specifically?

**Comment by L3onidass** [comment]
Ok and when should I expect arriving? I can't because, I tried again and there wasn't any message like you said but this time after pressing the create button I appeared in my wallet and that didn't happen last time. There was the error message about insufficient funds￼ so wallet did not create and I was forced to sent funds to the address which I gave you.

**Comment by polymorpher** [comment]
Did you send it from Binance? It shows Binance Gateway from the transaction id you pasted. Binance has an ongoing issue of not recognizing funds reverted to their address https://github.com/polymorpher/one-wallet/issues/93  The funds went back to their wallet, but they are not giving it to you. I have raised this issue to them before. They seem to be working on it, but they still haven't fixed it.

**Comment by L3onidass** [comment]
Yes I did. Unfortunately it's not the first time when Binance did not give me funds. Should I open the ticket￼￼?

**Comment by polymorpher** [comment]
Yes please. If I get any update from Binance I will also let you know

**Comment by polymorpher** [comment]
I can confirm Binance fixed it. I tested withdrawal on both binance.com and binance.us and it worked for me.

**Comment by L3onidass** [comment]
Thx
