### ISSUE TITLE
Transaction failed when sending one to one crazy wallet

### ISSUE THREAD

**Issue by BodieJ242** [polymorpher/one-wallet#127]
Sent Harmony one from Binance to the wallet address in the crazy wallet. It was successful from the Binance side but failed.

one1kdmfn8q8tpr24ysk2azrz2kgl02tz7pg09kfzm

Any suggestions? 
![Screen Shot 2021-09-12 at 9 44 25 PM](https://user-images.githubusercontent.com/88987689/133016305-f9888938-c287-4032-9fa5-0eaf363e8179.png)
![Screen Shot 2021-09-12 at 9 42 22 PM](https://user-images.githubusercontent.com/88987689/133016306-2722c815-b895-4bec-8be8-2b3c02374b03.png)

**Comment by polymorpher** [comment]
The amount is significant. I am reaching out to various teams to discuss a resolution. It is the same issue multiple people (including myself) encountered before and had their fund stuck at Binance:

https://github.com/polymorpher/one-wallet/issues/93
https://github.com/polymorpher/one-wallet/issues/123#issuecomment-915830355
https://twitter.com/polymorpher/status/1434385512362491906


I will also add a warning in the UI until Binance resolves the issue

**Comment by polymorpher** [comment]
Did you get a refund in your Binance account? They say you should have received it.

**Comment by BodieJ242** [comment]
Hey Polymorpher! I got it!

Thanks again! I appreciate your quick turnaround on this.  You made me want to continue following Harmony One.

 Should I try again sending to the wallet? 
Or wait for a moment? 

I'm okay waiting.

**Comment by polymorpher** [comment]
I just tested using my own accounts. Withdrawal from Binance to 1wallet still fails. And my money is not refunded to my Binance account. Let's wait until Binance fixes it.

**Comment by BodieJ242** [comment]
You are the truth! 

Blessings

**Comment by polymorpher** [comment]
I can confirm Binance fixed it. I tested withdrawal on both binance.com and binance.us and it worked for me.
