### ISSUE TITLE
1Wallet not Showing Harmony PUNK in 'Collectibles' tab

### ISSUE THREAD

**Issue by justhall** [polymorpher/one-wallet#128]
Wanted to test the new 1Wallet and NFTs.  Using the Harmonypunks.one site, I sent one of my punks to my 1Wallet address, confirmed the transaction and it never showed up in my 1Wallet.

Now I am showing it is linked to my 1Wallet address via the Harmony Punks website but just not visible.

**Comment by justhall** [comment]
Info:

Transaction ID:  0xb93b49d74e8905809eb7c0c5a5d3e73ba2910f449c5d247b81a86880e4601627

**Comment by polymorpher** [comment]
Just fixed it in https://github.com/polymorpher/one-wallet/commit/7d20fff2ae8a6204e99affb1ce1fadfbd4487550 and https://github.com/polymorpher/one-wallet/commit/53480761e4a2e5ec38288e82493a23c0b4a77778

HarmonyPunk has non-standard metadata (image sometimes points to an API that always returns error if not called from their website). The URL format is inconsistent. The image is hosted in private AWS servers/buckets, and has strange/restricted permission settings (not allowing queries for file headers). For these reasons, it is very challenging for other developers to correctly support showing Harmony Punk. I have to handle individual issues on a case-by-case basis.
