### ISSUE TITLE
Ability to remove a token from the 1Wallet

### ISSUE THREAD

**Issue by justhall** [polymorpher/one-wallet#129]
Say I transferred out all my FUZZ or whatever token and no longer wish to see it below in my list of tokens.  Currently there is no way to remove any tokens once they've been added.

**Comment by polymorpher** [comment]
I will add something in the next version to support that.

**Comment by polymorpher** [comment]
https://github.com/polymorpher/one-wallet/pull/154 added buttons to let users track/untrack NFT and tokens manually. See also https://github.com/polymorpher/one-wallet/issues/144#issuecomment-932732591 for limitations and improvements coming soon.

Please feel free to reopen if any new issue comes up
