### ISSUE TITLE
Copy/ paste address button does not work properly

### ISSUE THREAD

**Issue by boubou158** [polymorpher/one-wallet#130]
On mobile, while clicking on the button to copy paste the address, what is paste looks like "onetk...difi" with still the three dots instead of being the whole address. Hence, i am not able to store my address since i cant see it.

**Comment by polymorpher** [comment]
Sorry about that. Fixed in https://github.com/polymorpher/one-wallet/commit/bac473d644a14a28cb956ae0b72535ae3311cdda

**Comment by boubou158** [comment]
Thanks :)
