### ISSUE TITLE
Upgraded and lost domain

### ISSUE THREAD

**Issue by terence-truong** [polymorpher/one-wallet#132]
1Wallet asked to upgrade, and I upgraded then I saw the domain that I purchased is gone. Will this happen every time I upgrade?

**Comment by polymorpher** [comment]
I will add a button to reclaim domain in the next few days

**Comment by polymorpher** [comment]
It stayed with the old address. So any transfer made to the domain will still be forwarded to the new address. That button will transfer the domain from old address to the new address

**Comment by terence-truong** [comment]
Okay, sounds good. I'll wait for the button to reclaim the domain, and I'll close this issue. Thanks for getting back so quickly.

**Comment by polymorpher** [comment]
Try the reclaim feature? https://github.com/polymorpher/one-wallet/releases/tag/v0.13.1
