### ISSUE TITLE
google authenticator doesn't work w/ pixel phone

### ISSUE THREAD

**Issue by hakwanlau** [polymorpher/one-wallet#136]
when reading the QR code, somehow it works with the ipad, but no the auth on the pixel phone - there it just couldn't read it at all. perhaps it has something to do with this?
https://github.com/pterodactyl/panel/issues/1624

**Comment by polymorpher** [comment]
No. But I noticed scanning occasionally fails on my Nexus 6P. When that happens, I simply refresh the page and try another QR code, which often works. Have you tried?

**Comment by hakwanlau** [comment]
not really. tried several times , and tried both google authenticator as well as Authy. the error message read "Format not supported". but it works with the ipad. so strange!

**Comment by polymorpher** [comment]
Are you displaying the QR code on your iPad, but scanning it on Android? It won't work because Google Authenticator apps on iOS and Android have different capabilities in recognizing the code in scanning mode (but not for deep link, i.e. tap mode) with the iOS version recognizes more formats. The QR code displayed is tailored to OS and device type.

**Comment by hakwanlau** [comment]
yeah was displaying the QR code on a MacBook, with OS = BigSur, browser = Brave. 

does it mean it can't be resolved? it's not an uncommon setup though, MacBook + Pixel phone

**Comment by polymorpher** [comment]
No, on desktop the QR codes are all the same. What version of authenticator are you using? Very old versions can't recognize some formats.

**Comment by hakwanlau** [comment]
that's strange. so it was macOS 11.5.2. Big Sur, Brave 1.29.80, Google Authentica is just downloaded (after trying on an older Authy and doesn't work). phone = Pixel 3A, Android is latest ver

**Comment by polymorpher** [comment]
I will run a simulator and try later

**Comment by haolinj** [comment]
I've tried it with Android emulator: Pixel 3A with API level 30 (Android 11). Installed Google Authenticator in emulator and used it to scan the QR code, it is successfully scanned.
![test](https://user-images.githubusercontent.com/1297472/133888088-e75cd1b8-f4ab-4a10-b692-fa2e5b00ad0c.gif)

Can you check your Android version, is it Android 11 or 10? I will try to match your Android version exactly.

**Comment by terence-truong** [comment]
I also had this issue using the Brave browser and my Pixel 3XL, but when I refreshed the page and scanned the new QR code, it worked fine. For some reason, it's only the very first QR code that it has an issue with.

**Comment by polymorpher** [comment]
Fixed in https://github.com/polymorpher/one-wallet/commit/dfff4eb8c7d8b231074a2b6c70c74ba8168e5c4f . Try again?
