### ISSUE TITLE
Can not monitor many wallets on the same time?

### ISSUE THREAD

**Issue by vuquangbinh** [polymorpher/one-wallet#146]
Hi,

I created 2 wallets with 2 accounts in Authenticator but in the Wallet panel, it shows only 1 account. The rest account did not show. How can I monitor some wallets in the same Wallet panel on the same time?

**Comment by polymorpher** [comment]
If you created two wallets, it will show two wallets. Were both successfully created?

**Comment by vuquangbinh** [comment]
Yes, 2 wallets were created successfully. You can see in attached file
![Screenshot 2021-09-23 102247](https://user-images.githubusercontent.com/38254004/134450831-ff6384dc-8eeb-4fce-bc45-b95d4f6698e0.jpg)
![Screenshot 2021-09-23 102311](https://user-images.githubusercontent.com/38254004/134450838-d4f1f453-7dab-42f0-9782-45ea8008d490.jpg)
s.

**Comment by polymorpher** [comment]
I can only see 1 in the screenshot. What happens when you click "Create" and create another one?

**Comment by polymorpher** [comment]
This is what it looks like with 2 wallets:

![image](https://user-images.githubusercontent.com/913871/134459997-9fa3492c-5b5f-4520-95da-2dfcbfcea6a8.png)

**Comment by vuquangbinh** [comment]
I had created already 3 wallets and it still show only 1 wallet as in screenshot

**Comment by polymorpher** [comment]
What browser and settings are you using? I need to reproduce the error

**Comment by vuquangbinh** [comment]
I used both Brave and Chrome. Both got the same error

**Comment by polymorpher** [comment]
What URL are you accessing it from? I see some unexpected parameters from server logs

**Comment by vuquangbinh** [comment]
https://1wallet.crazy.one/wallets

**Comment by polymorpher** [comment]
I see you are creating a wallet using parameters that can only be set in expert mode or customized. Since you are an expert, can you record a full screencast video of what you did to reproduce the error?

**Comment by vuquangbinh** [comment]
https://user-images.githubusercontent.com/38254004/134476205-090c2b68-788d-467e-995a-39d1efa7f46c.mp4

**Comment by polymorpher** [comment]
00:19 and 00:49 - you didn't click "Create Now"

**Comment by vuquangbinh** [comment]
Ok I see, it's my fault. I missed this step. Thanks!

But can you impress users by animating that button? I think many people will miss that step like me.

**Comment by vuquangbinh** [comment]
I want to explain why I didn't hit the 'Create New' button. Because I thought if I press that button it will create another new wallet. Please can you elaborate a bit more so that more people understand that there is one more step to create a new wallet, that is to press that 'Create New' button.

Or you can change the word 'Create New' with a different word, for example 'Click here to finish creating a new wallet'.

Thanks!
