### ISSUE TITLE
execute the transaction is an error

### ISSUE THREAD

**Issue by saigoncoin** [polymorpher/one-wallet#147]
In general, there are many minor errors, even I can't enter 2fa because I can't enter the number because 
![Screenshot (105)](https://user-images.githubusercontent.com/31839061/134455673-7375d411-86dc-437a-825c-d9d3dc5e61ea.png)
I can't enter the number.

**Comment by polymorpher** [comment]
Do you still have the Google Authenticator entry? This "Recover" feature is meant to be used when you have lost it, therefore it wouldn't make sense to ask you to enter the authenticator code.

This particular error you have shown indicates the browser deleted part of the information stored for this wallet. This could happen when disk space is low and the browser silently cleans up some stored data to free up disk space. This may also happen for some older wallets or Safari iOS, which I intend to fix later. It seems your case falls under the former situation.

**Comment by polymorpher** [comment]
I am closing this issue since it is repetitious to #148
