### ISSUE TITLE
Restoring error - Aegis Authenticator

### ISSUE THREAD

**Issue by Wgsem** [polymorpher/one-wallet#151]
Using [Aegis Authenticator](https://github.com/beemdevelopment/Aegis) on a Pixel 5 (running GrapheneOS).

Created a wallet on my phone, tried to restore it on a laptop (running Linux Mint).
When scanning the QR generator by Aegis it gives an error 'Unrecognizable Code'.
Tried on two different browsers (Brave/FF) to see if that made a difference.

Can provide other details if necessary.

**Comment by polymorpher** [comment]
"Unrecognizable Code" is an error that is only generated by either (1) scanning a QR code in an address input bar, or (2) scanning a QR code in a wallet's home page via the "scan" icon on the top right. Neither is intended to scan a QR code exported by an authenticator. 

You said you were trying to restore a wallet. Did you type in the address of the wallet or scanning the address of the wallet first, before scanning the QR code exported by the authenticator? It sounds like you scanned the QR code from the authenticator in a place where it says to scan the QR code of a 1wallet - not the authenticator.

**Comment by Wgsem** [comment]
Sorry Aaron, I was scanning my auth. code where I should have scanned my address. 


The error I do get, in the next screen:
1) Open Google Authenticator
Go to Google Authenticator, tap ... -> Export accounts on the top right corner

Scanning the generated QR gives the following
'Failed to parse QR code. Error: TypeError: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object'

**Comment by polymorpher** [comment]
I will try this authenticator myself later this week to debug. Most likely there are some minor issues with how they implemented QR code export serialization (protobuf)

**Comment by polymorpher** [comment]
Added support in https://github.com/polymorpher/one-wallet/pull/157 . It is a good authenticator. Should release an iOS version
