### ISSUE TITLE
can we integrate transak as fiat gateway

### ISSUE THREAD

**Issue by lijiang2087** [polymorpher/one-wallet#155]
transak has been a great partner for harmony and they cover many countries and currency as a fiat on-ramp. let's integrate into 1wallet.

--
Link of technical documentation
https://www.notion.so/transak/Integrate-Transak-f43cbb5dc7fa4d068a044ef9589879bf

**Comment by polymorpher** [comment]
Yes, I will test with a non-production key at first

**Comment by polymorpher** [comment]
Is ONE already supported? Didn't see it in the list of selectable cryptocurrencies https://global.transak.com/

**Comment by polymorpher** [comment]
still waiting on transak to fix the issue that crypto gets automatically switched to ETH for US users
![image](https://user-images.githubusercontent.com/913871/140049124-460452a7-42e1-4d5f-8f1e-4394253d25f3.png)

**Comment by polymorpher** [comment]
Deployed using custom made country selector

![telegram-cloud-photo-size-1-4909288215538674161-y](https://user-images.githubusercontent.com/913871/140289269-dbfb9901-1e1e-493c-b302-dae61db9ff67.jpg)
