### ISSUE TITLE
Cannot restore 1wallet

### ISSUE THREAD

**Issue by StrongMindsHold** [polymorpher/one-wallet#16]
When trying to restore the 1wallet I can input the wallet address and scan the QR code but it gets stuck at the "Restoring your wallet" page. Will not get past the "Recomputing proofs for each time interval" check.

**Comment by polymorpher** [comment]
Wallets created prior to 6/28/2021 may have incorrect parameters during setup. This is fixed by https://github.com/polymorpher/one-wallet/commit/7bc808c0c9a2f89b3cbd08e79d34c1adc0a78e98

If your wallet is a brand new wallet, can you share with me the address so I can take a look at the contract?

**Comment by StrongMindsHold** [comment]
Let me create a new one and see if the issue persists.

**Comment by polymorpher** [comment]
Let me know if it happens again.
