### ISSUE TITLE
Stats are not showing correct

### ISSUE THREAD

**Issue by CroBizz** [polymorpher/one-wallet#162]
Hi I see that number of created wallets and balance is changing each time when I visit: https://1wallet.crazy.one/wallets
 
First time number of wallets when I visited site was 2681,after that I closed it and comed back for 2nd time and it was little bigger amount and 3nd time when I closed and opened wallet link it was again 2681 number of users and again lower balance then on 2nd site visit.

**Comment by hypnagonia** [comment]
explorer calculates sum of balances for a day
there's more than one api instances behind load balancer and each instance could have different cache expiration time 
so yes values could slightly vary with every request
https://explorer-v2-api.hmny.io/v0/1wallet/metrics

i will ask devops to enable "sticky sessions" on the balancer

**Comment by polymorpher** [comment]
Stats are now cached for 2 hours locally. https://github.com/polymorpher/one-wallet/commit/71a0b26a2592bc9b0ac2961e343c53235053bb02
