### ISSUE TITLE
More than 1000 ONE - How to claim remaining balance after wallet update?

### ISSUE THREAD

**Issue by starlygirl** [polymorpher/one-wallet#164]
I was prompted to install an update when I signed into my 1wallet yesterday. I had 1131.599 ONE and now that I've updated the wallet, there are only 1000 ONE in it. There were some instructions about how to move the rest over, but now I can't remember what I need to do to bring the remaining ONE into the updated 1Wallet. Please let me know what to do. Thank you in advance!

**Comment by polymorpher** [comment]
There are two options. You can send some money (e.g. 0.1 ONE) from your recovery address to the old 1wallet address. That will approve transferring the remaining 131.599 ONE to the new address.

The other option is to "Inspect" the old wallet address and manually transfer the remaining amount to the new address. See the second screenshot in https://github.com/polymorpher/one-wallet/releases/tag/v0.13.1

**Comment by starlygirl** [comment]
Thank you, the "inspect" method worked great.
