### ISSUE TITLE
Too Difficult to transfer wallet to another browser from the same computer.  

### ISSUE THREAD

**Issue by dastdx1847** [polymorpher/one-wallet#168]
I've tried moving my wallet from a chrome browser to the brave browser.  As previously noted, google authenticator bar code isn't recognized and requires a camera on the device.  Desktop computers may not have cameras attached to them, so an alternative way of inputting the google authenticator code(s) should be made available, particularly for devices that don't have cameras.

**Comment by polymorpher** [comment]
@dastdx1847  give the new import/export feature a try?
