### ISSUE TITLE
Informative error messages from emitted logs

### ISSUE THREAD

**Issue by polymorpher** [polymorpher/one-wallet#176]
Many users are confused when 1wallet prompts their transaction is "done", but in reality the transaction actually failed. For example, when the user attempts to send ONE beyond what their daily limits allow them to do, they would assume the transaction is successful, but it is in fact not so. Many users are unaware of the existence of such limit, which by default is 1000 ONE per day. The transaction https://explorer.harmony.one/tx/0x224d03f05e109e4ef71ebf6ae4d68a4dd0822f775584154cf05217f9be06c36b?activeTab=2 is an example. The error is only revealed through the log, which shows topic `0x55e3e9bfe128ba9adab893485d7dcbbbce711ba4ae2ab5154181467093f1d423`, that maps to event `ExceedSpendingLimit(uint256,uint256,uint256,uint256,address)`. See also https://github.com/polymorpher/one-wallet/blob/master/code/scripts/events-map.txt. 

The confusion comes from the fact that "done" only means the transaction is completed. It does not mean the operation necessarily succeeded. For security reasons (to prevent OTP re-use), 1wallet does not revert a transaction when authentication is successful but the operation is not. This mechanism is different from other wallets and common practice in smart contract, which simply reverts transactions when the intended operation fails. 

Accordingly, it is necessary to decode transaction receipts (which are returned by relayer after a transaction is completed) and display its content in human readable form to the user (within notification boxes). In addition to simple send, other operations may also result in error (such as recovery, upgrade, and others). Errors should be parsed, displayed promptly and intelligently, instead of expecting the user to decipher transaction logs in explorer.

**Comment by cylim** [comment]
@polymorpher 
Had spent some time understanding the current system, I am not sure what is the approaches to this issues.

Tried to check the receipts from the transaction, the event logs are not in the `tx.receipt` yet. Probably have to do another call to `method: hmyv2_getTransactionReceipt`, unsure whether if calling it right after the transaction, the log might be empty?

trx: [https://explorer.harmony.one/tx/0x58cbca4ac3628c5ba83c41d0a4416a630f977218a1a245fbf9c8a0fad058060d?activeTab=2](https://explorer.harmony.one/tx/0x58cbca4ac3628c5ba83c41d0a4416a630f977218a1a245fbf9c8a0fad058060d?activeTab=2)

<img width="573" alt="Screen Shot 2021-11-28 at 18 34 33" src="https://user-images.githubusercontent.com/5622951/143764361-b1deb5c5-af0a-41f1-94f5-a23245493dfb.png">


I was thinking of another approaches, which is using the contract event listener, but then I realized that the address recorded is destination address(which I can't filter by user owned wallets' address) and there might be different reasons/events why it failed. e.g. Insufficient Fund will fail too.
https://github.com/polymorpher/one-wallet/blob/b879de3815d3fe78550b9526ead97836c3d07a20/code/contracts/SpendingManager.sol#L43-L53

**Comment by polymorpher** [comment]
It's in the raw logs. We will need to map the emitted topics (in raw logs) to the event-mapping (see code/scripts/ - I pre-generated a mapping). We can then decode the data in raw logs from there, after identifying which event it belongs to.

**Comment by cylim** [comment]
Ah... forgot to check the rawLogs... Confirmed it is in it.

**Comment by minami81** [comment]
@polymorpher as per chat, would be great if you could enum the operation types

**Comment by cylim** [comment]
@polymorpher We can enum all failure events, which we have to track and show to users. If we code it in the code, we can have targeted message for each events.

or I will just use the event-map.txt(json) directly whenever there is a topic in the transaction logs.

e.g. 0x55e3e9bfe128ba9adab893485d7dcbbbce711ba4ae2ab5154181467093f1d423  
-> get ExceedSpendingLimit(uint256,uint256,uint256,uint256,address) 
-> parse to `Exceed Spending Limit`
-> message.info('Exceed Spending Limit') 
// In this case it is harder to have targeted message, hard to tell what the parameters are.

If there is more than one event/topic, all topics will be shown before the transaction complete message.

**Comment by polymorpher** [comment]
I am in favor of using hand made messages. Let's use event-map.txt to find which event it is, and have a message template for each event, including both success and failures.

**Comment by polymorpher** [comment]
I think we can close this off for now
