### ISSUE TITLE
Tokens Not Transferred to Frontier Wallet

### ISSUE THREAD

**Issue by cryptonaut007** [polymorpher/one-wallet#180]
Hello. I've transferred my ONE from my 1wallet to my Frontier wallet (copied and pasted the wallet address) for staking, but I still haven't received my tokens... The transaction hash says the transaction is "successful." I still see the token amount on my wallet. Is this a delay? Was the transaction successful? I want to stake my tokens on Frontier. I've been using Frontier to stake... Please help me.

Transaction hash: https://explorer.harmony.one/tx/0x7bc7907a40f2c5d6a9a8185260918d0171d24c21f2783f45e8e5a34fe0d798ca

Do I need to drop my 1wallet and Frontier addresses? Please advise. Thank you.

**Comment by polymorpher** [comment]
The transaction was not successful. The log says `ExceedSpendingLimit(uint256,uint256,uint256,uint256,address)`,  with data, 3448000000000000000000, 1000000000000000000000, 0, 86400, 0xB92D140A45CB3C33aE3B3C01402cfC21FD14EC19. In English, it means you tried to transfer 3448 ONE whereas your daily spending limit is 1000

**Comment by cryptonaut007** [comment]
> The transaction was not successful. The log says `ExceedSpendingLimit(uint256,uint256,uint256,uint256,address)`, with data, 3448000000000000000000, 1000000000000000000000, 0, 86400, 0xB92D140A45CB3C33aE3B3C01402cfC21FD14EC19. In English, it means you tried to transfer 3448 ONE whereas your daily spending limit is 1000

Unless my eyes deceive me or I lost the ability to read, when you click the link, the Harmony Block Explorer clearly indicates the status of the transaction as "Successful." 
![ONE](https://user-images.githubusercontent.com/93469974/139577853-674e85b1-1862-46ea-bcab-d2c764392dbb.JPG)

If I had seen the ExceedSpendingLimit log, I wouldn't have raised the question. Hehe. 

Anyway, thanks for looking into this, Aaron. I'll try sending 1000 a day and see if it works. Lastly, if you could tell me where you found that log, I'd probably write a guide for other users ("In English") to refer to in the future. :) 

Thanks again~

**Comment by polymorpher** [comment]
It's under the third tab. The explorer status is sometimes misleading. I plan to fix it in 1wallet UI some time next month https://github.com/polymorpher/one-wallet/issues/176

**Comment by cryptonaut007** [comment]
> It's under the third tab. The explorer status is sometimes misleading. I plan to fix it in 1wallet UI some time next month #176
