### ISSUE TITLE
No way to edit Recovery Wallet

### ISSUE THREAD

**Issue by Thorsr20** [polymorpher/one-wallet#182]
Currently there is no way to change my recovery wallet address. Initially I used an exchange wallet just to have something but I’m trying to change the address due to Binance not accepting smart yet.

**Comment by polymorpher** [comment]
I suggest simply creating a new wallet. I am evaluating a few options to do this in a future version. It will not be easy, and doing it will have the strongest security requirement since if we allow the recovery address to be easily changed, an attacker who gained one opportunity to use your wallet may change it and steal all the funds.

**Comment by Thorsr20** [comment]
Thank you for the reply. I tried to send it all to my Guarda wallet but it never went through. I wasn't sure if it was because it is a large amount of coins and is over the limit or what. It did go through with an initial smaller amount first. Should I try again... maybe with a different 1 wallet? My only concern is that it triggers sending it to the recovery wallet and is lost forever. I appreciate the help.

**Comment by polymorpher** [comment]
By default there is a 1000 ONE daily spending limit. What's your address?

**Comment by Thorsr20** [comment]
one10sxrlwzrv9tghrrqyrra7rynxtwvuate2nf406

**Comment by Thorsr20** [comment]
one10sxrlwzrv9tghrrqyrra7rynxtwvuate2nf406

**Comment by polymorpher** [comment]
I am speaking with Binance to see if they can make sure the customer service will recognize your deposit when you do the recovery.

**Comment by Thorsr20** [comment]
Incredible! Thank you so much.

**Comment by Thorsr20** [comment]
Hi. Any update or word from Binance?

**Comment by polymorpher** [comment]
Not yet. I will follow up again next week

**Comment by polymorpher** [comment]
I spoke with Harmony bridge developers, who voiced the same concern because some other people recognized the same issue affects bridge users as well. I noticed that people used to have the same issue with Ethereum smart contract deposit to Binance, but that appear to have been fixed some time in 2020. 

We know that Binance relies on Harmony SDK to decode transactions and check for deposit. But it is unclear how they are using it. So I also spoke with Harmony SDK developers, who are more than willing to make changes so that Binance can regonize contract deposits, like they do for Ethereum. We communicated with Binance and are waiting to hear back

**Comment by polymorpher** [comment]
Would you be able to send ONE from that recovery address? I am adding a feature that let you adjust spending limit in the next version. If you can send ONE, you would be able to upgrade an migrate the asset (using your recovery address to send 0.1 ONE to approve), then use the new feature to adjust the limit, and get the assets out

**Comment by Thorsr20** [comment]
Sorry for the late response I wasn't expecting to hear from you that soon. Yes I can send one from that recovery address just let me know when.

**Comment by Thorsr20** [comment]
My One is gone! It had a balance when I first pulled it up but then it refreshed and has a zero balance.

**Comment by polymorpher** [comment]
it's still there, probably network error. Sometimes the public RPCs block people if too many requests were sent during a short period of time

https://explorer.harmony.one/address/0x7c0c3fb84361568b8c6020c7df0c9332dcce7579

**Comment by Thorsr20** [comment]
Thank you I was nervous. So can I get back to my wallet without having to restore? And if I restore will that trigger anything being sent to my recovery wallet? No rush. Thank you again for the help.

**Comment by Thorsr20** [comment]
I can definitely send one from the recovery account. Can you just confirm that I can restore my account without triggering a send to the recovery wallet. I haven't been able to view it for the last two weeks because I wasn't sure what the restore would do. Once I get back in I can send from the recovery wallet. Thanks

**Comment by Thorsr20** [comment]
Sorry I know your busy but I restored my wallet and would like to know when I should send one from my recovery wallet and then how to go about changing the the address. Thanks

**Comment by polymorpher** [comment]
The next upgrade is big, so it is taking a while, perhaps deployed some time during this week.

**Comment by polymorpher** [comment]
v15 is out - give it a try? See spending limit changing rules in release notes

**Comment by Thorsr20** [comment]
Ok will do. Thank you

**Comment by Thorsr20** [comment]
Still waiting for Binance to allow withdrawals so I can send one from recovery and upgrade to v15. I'll keep you posted.

**Comment by Thorsr20** [comment]
Ok so Binance US doesn't allow you to send less than 60 One so I can't send .1 to upgrade. the only option I see is to renew my wallet so I can use v15 features to increase my spend limit. Does that sound right? Also what does skip this version mean?

**Comment by polymorpher** [comment]
You can send any amount as long as it is not 1.0 ONE. 60 ONE is fine.

**Comment by Thorsr20** [comment]
I got an error after 4 failed attempts. ![image](https://user-images.githubusercontent.com/93657846/151678378-0098afa4-02b2-4763-b6ac-c59a38e0acf4.jpeg)

**Comment by polymorpher** [comment]
Try again? I think it is Harmony blockchain / public RPC server's delay. It seems to happen from time to time, over the last 2-3 weeks. I am about to move to a private RPC server

**Comment by Thorsr20** [comment]
Ok I'll try soon. Thanks

**Comment by Thorsr20** [comment]
Wallet upgraded but only 1000 one transferred and the reclaim says there are zero assets to claim even tho inspection shows them there.

**Comment by polymorpher** [comment]
Have you sent 60 ONE to the original address?

**Comment by Thorsr20** [comment]
I thought you were supposed to send it to the new address so I did that. Then I sent some to the old address about an hour ago after reading your comment but still nothing.

**Comment by polymorpher** [comment]
Your recovery address is `0x2930Ec0965F8fA06a448d7E6315B395Bf709D692`. You need to send from that address to trigger something

**Comment by Thorsr20** [comment]
I sent to the old and new address both starting with (one). From the recovery wallet mentioned. I don't understand the the addresses starting with 0 though. What is the difference? As soon as I type an address starting with 0 Binance says it's not a valid one address. Sorry I don't understand.

**Comment by polymorpher** [comment]
The two formats are equivalent and are 1:1 mapped. Use the toggle on the top right to switch.

![image](https://user-images.githubusercontent.com/913871/152046551-24baa680-fdcf-46f0-b986-a36ef11656c8.png)

**Comment by Thorsr20** [comment]
Binance US will not let me send to any address that doesn't start with "one". Once I paste the address starting with one the error goes away and I can preview the withdrawal. 
![image](https://user-images.githubusercontent.com/93657846/152070415-29f9a02e-c3a4-40ff-b8ae-c61373f52476.jpeg)

**Comment by Thorsr20** [comment]
I'm assuming it's because the recovery wallet is in a "one" format but I can't change that

**Comment by polymorpher** [comment]
You can use explorer to translate between `one1...` and `0x...` addresses

**Comment by polymorpher** [comment]
Also, when I said your recovery address is `0x2930Ec0965F8fA06a448d7E6315B395Bf709D692`, it means you need to send **from** that address to your old wallet address `0x7c0c3fb84361568b8c6020c7df0c9332dcce7579` (use explorer to translate to `one1..` if you need that format)

**Comment by Thorsr20** [comment]
Ok as long as it doesn't matter which format then it should of worked. I've sent to my old address from my recovery address using the one format and both are correct. The recovery address is the only one ive ever had and has been right from the start. Ive triple checked. Are you sure it still works sending 60 one? I don't know what else I can do.

**Comment by Thorsr20** [comment]
Ok now I see on explorer the transaction shows it coming from a different wallet address but that doesn't make any sense. When I click deposit into that recovery address it gives me the right address, the one that matches. The wallet that it shows in the transaction isn't my address and when you click on it the balance it shows is in the millions which is definitely not mine. Does Binance use some sort of weird code or something? I'm sorry I'm not more technical. It just doesn't make sense.

**Comment by Thorsr20** [comment]
I think what's happening is when I send from Binance it's using a collective address for all the one in Binance so no matter what I do the from address will never be the address that I put in as my recovery. So what are my next options. Am I still able to send from my old wallet even after the upgrade? I could just do 1000 one per day.

**Comment by polymorpher** [comment]
Yes, if you can't send from recovery address, 1000 per day is the second best thing

**Comment by polymorpher** [comment]
Closing this off for now. Sorry it wasn't working out as expected. Let me know if I can help with other things
