### ISSUE TITLE
Loss of funds

### ISSUE THREAD

**Issue by Talawah1** [polymorpher/one-wallet#183]
I did the update this morning and lost 9001 ONE. These are the steps I missed, but I didn’t see it before inputting my google Authenticator password
![4733C673-368D-4698-B018-26002B85D5B7](https://user-images.githubusercontent.com/93663473/140079132-e98cf7f9-9781-479f-869c-aef6acf90678.jpeg)
Is there a way to recover the missing funds?

**Comment by polymorpher** [comment]
Can you post your wallet's address? The address in the screenshot is missing one character

**Comment by polymorpher** [comment]
Nevermind. I missed a character

**Comment by polymorpher** [comment]
Can you send 0.1 ONE from `one1aus70j0uhamwzaq7sdhkc2re2pz5nv7u2hwu3n` to `one1w4marru9c5996sjmaa7v8zsn6am3q4faq3hg85`?

**Comment by Talawah1** [comment]
I’ve been trying to, but I used the recover feature thinking it would help. Now the wallet is deprecated

**Comment by polymorpher** [comment]
With more than 25000 gas

**Comment by Talawah1** [comment]
Okay, I’ll try

**Comment by Talawah1** [comment]
Still not working 
![Uploading CE1E781E-42F0-43C2-A0C4-AB4DEE325819.jpeg…]()

**Comment by polymorpher** [comment]
I saw the latest transaction was still 25000 gas (= 0.0001 / 0.000000004) https://explorer.harmony.one/tx/0x53848d84256194e1ee0378ab62b24dfffb2d21ff20ec7f2c47b905318c8ad5a7 . You changed gas price, not gas

**Comment by Talawah1** [comment]
Oh, okay. Trying again

**Comment by Talawah1** [comment]
![image](https://user-images.githubusercontent.com/93663473/140184326-b4e93853-456f-44c3-83d7-bca65e206211.jpg)
Same issue

**Comment by polymorpher** [comment]
I calculated, you need 59552 gas. Try 60000?

**Comment by Talawah1** [comment]
![image](https://user-images.githubusercontent.com/93663473/140185447-237f9967-4bc7-4590-941b-94c87fc26531.jpg)
Same message. 
Do you think it may be because I used to recover funds feature?

**Comment by polymorpher** [comment]
No. Sorry I calculated it wrong. If you send 1.0 ONE, it will need 71387 gas. So 80000 is enough. If you send something other than 1.0 ONE, say 0.1 ONE, it will need 59552. The difference is if you send 1.0 ONE, the funds will go to your recovery address. If you send something other than 1.0 ONE, the funds will go to your new address

**Comment by Talawah1** [comment]
Okay, I’m trying again

**Comment by Talawah1** [comment]
![Uploading C65D40B2-8D0C-4002-8B25-91F1A68ABC4D.jpeg…]()
Awesome. It’s back! Thank you very much!!

**Comment by polymorpher** [comment]
You are welcome. Sorry for the confusions. The upgrade process sucks. I will think of a way to fix it in the next version

**Comment by Talawah1** [comment]
I don’t think the process was the issue. I didn’t the warning noticed about the high value wallet before inputting the google Authenticator password. Maybe just switch that part up, so there’s a notice before the password

**Comment by Talawah1** [comment]
I have just one more question. Since I used the wallet recovery option on this 1wallet account, and the wallet is deprecated, will I have to set up a new 1wallet with google Authenticator to continue using 1wallet?

**Comment by polymorpher** [comment]
If you used the "Recover" feature on the UI, the secret which triggers recovery would be exposed through that transaction. The same secret could trigger recovery on the new (upgraded) wallet, since the upgraded wallet is controlled by the same authenticator codes. So under this scenario, the new (upgraded) wallet should be considered deprecated and should not be used (and the UI should suggest so).

If you triggered recovery by sending 1.0 ONE from the recovery address (which you did 3 hours ago) to the old wallet address. It is fine to continue using the new wallet. The old wallet, after recovery (by you sending 1.0 ONE after the upgrade), is basically severed away from the new wallet.

**Comment by Talawah1** [comment]
Okay. I have to figure out how to access the new wallet

**Comment by Talawah1** [comment]
On never mind. I see what you’re saying. So I should create a new wallet

**Comment by Talawah1** [comment]
I used the recover feature, so the upgraded wallet is now deprecated as well

**Comment by polymorpher** [comment]
I made the UI better like you said

![image](https://user-images.githubusercontent.com/913871/140270523-7f2a6c8e-edbd-48e2-b85f-574eaa73338e.png)
