### ISSUE TITLE
Sent 41 one from 1wallet - no transaction even showing on the block explorer?

### ISSUE THREAD

**Issue by githubuser105** [polymorpher/one-wallet#185]
I sent 41 one from my 1wallet to one1helpj8hdp0yr74fs0m9sd7ldqmgykydhmvzsle

The 41 one has been deducted from my 1wallet but when I check the block explorer it does not even show any transaction out from my 1wallet address?

**Comment by githubuser105** [comment]
Interesting that the receiving address shows 41 one as a balance with no transaction either.

**Comment by polymorpher** [comment]
It shows up under "Internal Transactions". The explorer as of now only has minimal support for displaying contract-based value transfer
https://explorer.harmony.one/tx/0x565df45045717dcda9ccf9385140f803cd2e7d166049ac9c4f82a3e977c9f2db?activeTab=1
