### ISSUE TITLE
Error after upgrading to new wallet

### ISSUE THREAD

**Issue by dietbald** [polymorpher/one-wallet#186]
Just before the upgrade I swap BUSD 0.34 to ~1.1ONE 

Next I upgraded my account to the new wallet. 

Now the BUSD and the 1.1 ONE is gone 

New wallet address : one1umj8d4q5l4x9kc24265s5f2xe4l94c5cwkqhtj

**Comment by polymorpher** [comment]
In About tab you can find the old wallet address there, which you can inspect and manually transfer the BUSD out to the new address. It will be automatic in future versions

**Comment by dietbald** [comment]
Thank you, that worked
