### ISSUE TITLE
Unable to withdraw ONES

### ISSUE THREAD

**Issue by DavidBanh5** [polymorpher/one-wallet#187]
Hi, I have a problem trying to withdraw ONES from the 1wallet. I tested and was able to send 1 ONE to my 1wallet however when I try to withdraw from 1wallet to my harmony extension wallet I can't.

**Comment by polymorpher** [comment]
Can you provide more information? What does "can't" mean and what are the addresses you are talking about?

**Comment by DavidBanh5** [comment]
![image](https://user-images.githubusercontent.com/28848965/140684922-4c99b362-2e6a-4cf7-be72-233a743c43cb.png)

When I hit max, it gives me 0. I've tried inputting an amount manually but the transaction shows I sent 0 ONES.

This is the address of my 1wallet:
one19d53exzu4ys2qn0h0u35lst5vr5d0hvg30vc4q

**Comment by polymorpher** [comment]
The actual amount you sent out are displayed under "Internal Transactions" when you examine a specific transaction. The explorer is not doing a good job on displaying value transfers in contracts. See also https://github.com/polymorpher/one-wallet/issues/180 and https://github.com/polymorpher/one-wallet/issues/185. 

For example here are some transfers you made: https://explorer.harmony.one/tx/0x8c8491c95ed41affd914a5baac0dda05a25b309e80e584b5929a15af07972c4b?activeTab=1

As to why you get 0 when you click "max", it is a bug. I am fixing it now.

**Comment by polymorpher** [comment]
fixed

**Comment by DavidBanh5** [comment]
Oh great! It seems to work now!

Thank you! :)

**Comment by polymorpher** [comment]
That will be the limit for the day. You can create a higher limit wallet - just follow the link right after you create a regular wallet
