### ISSUE TITLE
Wallets not displaying at 1wallet.crazy.one

### ISSUE THREAD

**Issue by CharleyBAZ** [polymorpher/one-wallet#188]
I used my desktop bookmark to navigate to 1wallet.crazy.one and when I select the wallet tab, my wallets are no longer there.  Can somone advise or direct me to any information on what might have happened to the wallet I had set up?  Thanks,

**Comment by polymorpher** [comment]
It is unclear what happened in your computer. It could be that your browser automatically deleted some stored data because your hard disk is running out of space. You can use Restore the restore the data

**Comment by CharleyBAZ** [comment]
Thanks, I did recently clear history and cache.

It seems that to restore the wallet, you need to know the wallet
address...I can maybe find it from an old transaction but is that the only
way to restore the wallet?  Thanks

**Comment by polymorpher** [comment]
Yes for now. After I am done with https://github.com/polymorpher/one-wallet/issues/172 you won't need to find the address in the future. It will be determined automatically

**Comment by CharleyBAZ** [comment]
Thanks for the help and feedback.  I was able to restore the wallet by exporting from Google Authenticator.  When I restored, it asked me to upgrade, which I did.  When finished, it asked me to upgrade again and I did it again but got an error.  Nevertheless I have restored my Neutral Exhaust Quarter Wallet.  Thanks,

**Comment by polymorpher** [comment]
Great to hear. I will look into the error. It's probably caused by network delay but there should be some remedy
