### ISSUE TITLE
Wallet Connect

### ISSUE THREAD

**Issue by polymorpher** [polymorpher/one-wallet#193]
Support for Wallet Connect has long been contemplated (see https://github.com/polymorpher/one-wallet/issues/5 section VI, and https://github.com/polymorpher/one-wallet/issues/73), but its implementation was repeatedly postponed in favor of features of higher importance. Since then, demand and use cases for mobile 1wallet have grown, and almost every dApps now provide Wallet Connect option. 

We already have various pieces ready for executing Wallet Connect instructions (e.g. call, sign, transfer, and others). We still need to implement the components that listen to Wallet Connect socket data and translate the instructions to call appropriate components in 1wallet. The amount of work is non-trivial but it should be feasible to complete the whole thing in December

**Comment by itwantid** [comment]
https://www.bestchange.ru/converter/

**Comment by itwantid** [comment]
I was hacked here today

**Comment by itwantid** [comment]
I was hacked here today

**Comment by polymorpher** [comment]
Done
