### ISSUE TITLE
Wallet had two consecutive upgrades. Asset disappeared

### ISSUE THREAD

**Issue by BritishBully** [polymorpher/one-wallet#194]

**Comment by BritishBully** [comment]
It allowed me to create 2 upgrades to my existing 1Wallet  wallet, creating 2 wallets, which I didnt want,  and neither one has my orginal 1xOne.
harmonyoneincome.crazy.one

**Comment by polymorpher** [comment]
I don't understand what you meant by "allowed [you] to create 2 upgrades". Can you elaborate? I see a chain of upgrades and the latest address `one14gsdzwce9cmaatvk90dnk2lyxpzaxrrjwvn000` has ~1 ONE, which you originally had

**Comment by BritishBully** [comment]
The upgrade to newer version screen  didnt go away after I completed it the first time, so I did it a second time, and ended up with 2 wallets. When I look at my harmonyincome.crazy.one  walles I see two wallets inside, neither of which contains any ONE. I dont even see the latest address.

**Comment by BritishBully** [comment]
I managed to find that wallet you mentioned using "About" and upon inspection I see that 1 x ONE, but then when I go to reclaim it it says 0 types tracked and it doesnt reclaim it. I guess I have to send it out?

**Comment by polymorpher** [comment]
You can send it out to your latest address. In the next version, The issue with upgrade is probably caused by network delay. I will fix it in the next version. I will also display aggregated assets in the next version, so it won't appear as if the assets were lost in any situation.

**Comment by BritishBully** [comment]
OK, I guess I'll wait till next version then to reclaim.
