### ISSUE TITLE
Restore 1wallet

### ISSUE THREAD

**Issue by dpro8** [polymorpher/one-wallet#195]
I created a 1wallet and it has since disappeared. When I try to restore my wallet it's asking to allow my computer camera to scan QR code from exported Google Authenticator. When I scan the QR code from google authenticator (my  previous setup 1wallet) it says unrecognizable code. Work around on this issue? It's a small amount of ONE but I would still like to recover it. Thanks

**Comment by polymorpher** [comment]
There are two scanning prompts. One is the address bar, where it is expecting a QR code representing an address (the image the wallet asks you to save). The other is a scanning window with detailed instructions on the top. It is expecting the QR code exported from Google Authenticator. A lot of people get confused between these two. Have you checked whether this is the case?

I plan to add more friendly instructions in the next version.

**Comment by dpro8** [comment]
I'm not sure to be honest. This is what I'm seeing ![image](https://user-images.githubusercontent.com/83175204/141868790-9e262da7-6fce-4f51-b2f5-0b6c4f589f19.jpeg)

**Comment by polymorpher** [comment]
This is where you provide the address or a QR code presenting the address. The exported QR code from Google Authenticator, in this version, does not represent the address. (But in the next version address can be inferred from that - but it won't work retroactively to older wallets)

**Comment by polymorpher** [comment]
I see the message is a bit confusing. I will fix it later today

**Comment by dpro8** [comment]
The QR code from
Authenticator is the only thing I have and won't recognize. So without the address I can not restore?

**Comment by polymorpher** [comment]
Usually, your address can be easily looked up in the explorer by looking at the transactions which sent assets to your wallet. It's all public record. Can you find those?

**Comment by dpro8** [comment]
Ok, I will look into finding it that way. Thanks for the info

**Comment by dpro8** [comment]
Probably a long shot. But is the wallet name searchable or is that just a local reference to distinguish 1 wallets?

**Comment by polymorpher** [comment]
Name is local. If you remember when you created the wallet, I can dig into the server log and try finding it from a pile of bytes.

**Comment by dpro8** [comment]
Around October 27th approx 1k ONE

**Comment by cylim** [comment]
@dpro8 
Have you make any transactions with the account, like sending or receiving ONEs from/to another address?
I can try to find the transaction related to your address from the explorer. :)

e.g. If you have transferred ONEs from CEX or other address, can retrieve your wallet address from there.

**Comment by dpro8** [comment]
I have made no transactions, just deposited the initial ONE to create the account.

**Comment by polymorpher** [comment]
The "initial deposit" is a transaction. Also creating a wallet does not require deposit

**Comment by dpro8** [comment]
Absolutely no way to use Google authentication to restore the wallet?

**Comment by dpro8** [comment]
Restored and upgraded wallet. Thanks

**Comment by polymorpher** [comment]
Great, sorry for the inconvenience
