### ISSUE TITLE
Address book management

### ISSUE THREAD

**Issue by polymorpher** [polymorpher/one-wallet#196]
Currently, new addresses and their labels are automatically saved to a local state. When addresses are found to correspond to a domain, the domain is used in lieu of a label. Right now, there are ways to delete saved addresses (simply by clicking X when addresses show up), but no way to edit them. Moreover, addresses of deleted wallets are not automatically removed. The result is saved addresses blow up very quickly, and after using the wallets for a while, the users generally see a bunch of irrelevant addresses at first when they click the address input box.  

We should allow addresses to be edited, by adding an edit button, in addition to existing delete button (X). The edit prompt could be a popover, or simply leading the user to a dedicated page where all saved addresses are listed and can be managed. As usual, modal should not be used.
 
References for starting point:
https://github.com/polymorpher/one-wallet/blob/master/code/client/src/components/AddressInput.jsx

**Comment by cylim** [comment]
- [ ] Able to edit address and label
- [ ] Able to remove address when wallet is deleted
