### ISSUE TITLE
Convert 1USDC to ONE gives you wrong value

### ISSUE THREAD

**Issue by dietbald** [polymorpher/one-wallet#204]
When trying to swap 1 1USDC to ONE , it is also impossible to complete the swap 

![image](https://user-images.githubusercontent.com/1293151/144751137-e3ecd379-3a3b-404d-9fad-96e527a27ae5.png)

**Comment by polymorpher** [comment]
Was the amount automatically filled? It does not appear so. Also you do not have any 1USDC balance to swap from

**Comment by dietbald** [comment]
I do have balance in the wallet for it. I thought I actually transfered 1 1USDT and 1 1USDC to the wallet, but I might have been wrong. I also dont seem to see the transaction in the block explorer in the HRC20 tab

![image](https://user-images.githubusercontent.com/1293151/144751254-0ebf0473-e070-49d7-83d6-32307e4c23cd.png)

**Comment by polymorpher** [comment]
I will look into this. I think it might be the balance in Swap page is out of sync with the balance on main page. There may be an error on the number of decimal points that are supposed to be used. And the large number is caused by either that or a divide by zero error.

**Comment by polymorpher** [comment]
@cylim  if you have time - feel free to take a look as well

**Comment by dietbald** [comment]
1usdc, 1usdt and AAVE seem to have similar issue 

![image](https://user-images.githubusercontent.com/1293151/144752368-26301fcc-da0b-4c7c-88db-1b9f31b95fba.png)
![image](https://user-images.githubusercontent.com/1293151/144752380-c21a9301-058d-4d18-8e25-1465112fc231.png)

**Comment by cylim** [comment]
@dietbald when you select the usdc, there are two USDC, select the one with squared icon instead of the rounded icon.

<img width="186" alt="Screen Shot 2021-12-06 at 16 05 17" src="https://user-images.githubusercontent.com/5622951/144809900-851bdd41-c875-4515-bc95-5bd5ab141832.png">

**Comment by cylim** [comment]
@polymorpher  After removing the default tokens, the AAVE pricing still incorrect, probably because of liquidity issues in Sushi Swap. I need to spend more time to look into it.

And we might need to update icons for some tokens.

**Comment by dietbald** [comment]
@cylim  I get the error for both of the Tokens, see in the picture, also the balance doesnt seem to come through as well 

![image](https://user-images.githubusercontent.com/1293151/144842781-8e404ae7-6318-465d-ad06-f5dd7444f1f4.png)
![image](https://user-images.githubusercontent.com/1293151/144842855-f0e62e9b-006f-4461-9f1c-05bec2f702e5.png)

![image](https://user-images.githubusercontent.com/1293151/144842974-f3c353cc-a7f5-4baa-a62a-eb8796592b30.png)

**Comment by polymorpher** [comment]
@dietbald the latest changes should have fixed some related issues, but I am not sure whether they are exactly the issues you faced. Can you check?

One thing I noticed on your screenshot is 1USDC and UST don't have any icons, which suggest that they might not be the USDC / UST tracked by 1wallet. Where did you get these tokens?

If the issues  still remain, can you record a video?

**Comment by polymorpher** [comment]
AAVE has insufficient liquidity on Sushiswap. I will update error message (currently this error only shows when you have both amounts in the input boxes)

**Comment by polymorpher** [comment]
hold on -  I am fixing a few other things

**Comment by polymorpher** [comment]
ready now

**Comment by polymorpher** [comment]
Let me know if this remains an issue

**Comment by dietbald** [comment]
All seem to be working great now, thanks
