### ISSUE TITLE
Can't send One tokens from my 1wallet

### ISSUE THREAD

**Issue by Lentz70** [polymorpher/one-wallet#208]
After trying to send one token to another wallet, the token did not leave, but since then I just can't send tokens anymore. I only got "validation error". So my money are actually stuck in my 1wallet\\Thanks

**Comment by cylim** [comment]
@Lentz70 Can you provide the wallet address?

**Comment by Talawah1** [comment]
Im having the same issue

**Comment by cylim** [comment]
@polymorpher seems like The relayer HTTPS cert expired.

**Comment by Talawah1** [comment]
Is there a solve for the problem?

**Comment by cylim** [comment]
@Talawah1 It should be quick fix. I am not sure when @polymorpher will be available.

One workaround is to go to https://relayer.onewallet.hiddenstate.xyz/ and trust the site. (NOT RECOMMENDED)

**Comment by Talawah1** [comment]
Okay, thank you very much. I'll wait

**Comment by polymorpher** [comment]
Sorry about that. I will set up a few more relayers over the next few weeks.

**Comment by polymorpher** [comment]
Also, the certificate is renewed. The issue should be fixed.

**Comment by polymorpher** [comment]
Leaving it open for now since @Lentz70 never replied and confirmed whether it is the same issue

**Comment by Talawah1** [comment]
Sweet. Thank you so much!

**Comment by polymorpher** [comment]
@Lentz70 please reopen if the issue persists

**Comment by Lentz70** [comment]
HI There

one1zgep0zqjd8rdrpxya4c5he3lcul429shl704z7

This is my adress

The problem it's still there, nothing changed

***@***.***(https://github.com/Lentz70)

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
