### ISSUE TITLE
Can't send One tokens from my 1wallet

### ISSUE THREAD

**Issue by Lentz70** [polymorpher/one-wallet#211]
Same issue #208 

Now when I try to send ONE from 1wallet it appears "done" - but the money does not leave.

So my tokens still stuck in wallet

wallet adress:
one1zgep0zqjd8rdrpxya4c5he3lcul429shl704z7

Thank you

**Comment by Lentz70** [comment]
Update - it worked if I sent only 1000 One

There is a 1000 ONE limit per transaction from 1 wallet?

**Comment by polymorpher** [comment]
no, 1000 per day, it says that when you create the wallet, and provides an option to create one with higher limit. See also https://github.com/polymorpher/one-wallet/issues/176. The error message will be fixed when we get to that

**Comment by polymorpher** [comment]
![image](https://user-images.githubusercontent.com/913871/145803190-fdd00336-b604-44b6-9a32-4a569b93d685.png)

**Comment by polymorpher** [comment]
@haolinj @cylim Let's think of a way to make this limit more prominent, so users don't get confused

**Comment by Lentz70** [comment]
i see, thank you a lot - I missed that :)

It's now to late to upgrade my wallet to a higher limit?

**Comment by polymorpher** [comment]
Yes, but you can set a recovery address and use recovery to get your money out. Then create another wallet with high limit. 

The next version will support changing limit by 2x per day (or per spend limit interval, if custom set).

**Comment by cylim** [comment]
@polymorpher 
we can show the limit and allow to select advanced mode before scanning the qr code?

**Comment by cylim** [comment]
<img width="310" alt="Screen Shot 2021-12-14 at 15 43 47" src="https://user-images.githubusercontent.com/5622951/145954446-ed82af40-649b-41a1-919e-aba2b0af6d1b.png">
And show the spending limit under the 1 ONE (left aligned)
