### ISSUE TITLE
Не верно отображается остаток на счету

### ISSUE THREAD

**Issue by Gaydaienko** [polymorpher/one-wallet#213]
Не верно отображается остаток средств на балансе. 
![photo_2021-12-16_15-48-51](https://user-images.githubusercontent.com/96248791/146393662-e282799d-70ca-4856-b54a-b5b7fda6a26b.jpg)
![photo_2021-12-16_15-48-39](https://user-images.githubusercontent.com/96248791/146393685-25579bb8-905c-47bd-a0c2-a1075c0afe4a.jpg)

**Comment by polymorpher** [comment]
English please
