### ISSUE TITLE
1wallet have dissapeared

### ISSUE THREAD

**Issue by Mike3-www** [polymorpher/one-wallet#218]
Using Firefox - wallet is gone after clearing history from browser -how do i restore - i have Google authenticator but it asks me to use camera which i dont have (ayyached to my desktop) -Please help to recover Wallet adress one1draf2a8n4t3ckksywq87gvf5pc6dmtextjkzvq

**Comment by polymorpher** [comment]
Resolved in https://t.me/the1wallet
