### ISSUE TITLE
Unable to recover 1wallet

### ISSUE THREAD

**Issue by ttrenary** [polymorpher/one-wallet#232]
### Discussed in https://github.com/polymorpher/one-wallet/discussions/231

<div type='discussions-op-text'>

<sup>Originally posted by **ttrenary** December 26, 2021</sup>
Hi - I apparently cleared all my browser data in ALL my browsers at some point and cannot restore my 1wallet with address: one1gtgd4e9atlk499arnwn4p3l99f2safhtlxtzxg 

It was created on 11/21 and I transferred a small amount of ONE from my main Harmony wallet one17dext3568agvs53vj2e4kmqetfwplhvydekwjg

Today I tried recovery using the first address and it would not recognize the QR code generated by the Google auth app. No errors - just totally didn't even think it was a QR code seemingly. I tried uploading the saved QR code (a .png file) and got a "Failed to parse QR code. Error: TypeError: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object" error.

Any help in recovering my wallet would be greatly appreciated.</div>

**Comment by polymorpher** [comment]
Followed up in the linked discussion thread.
