### ISSUE TITLE
Sef Wallet QR code is not recognized for fund transfer QR code scanner

### ISSUE THREAD

**Issue by CharleyBAZ** [polymorpher/one-wallet#233]
Hello, I have tried on several occasions to send funds from my 1 wallet to another external wallet by scanning the QR code.  Each time I attempt this, it tells me "unrecognizable code".  I then type in the address into the 1 wallet and it sends fine.  I am attempting to send from my 1 wallet on desktop to a SEF wallet on Android mobile.  Thanks for any feedback and let me know if you need any additional information.

**Comment by polymorpher** [comment]
Each wallet has their own QR code format. 1wallet recognizes a very specific format of QR code (something representing a URL starting with `https://1wallet.crazy.one/`, or just an address). Can you paste some QR code from SEF wallet so I can add support to those?

**Comment by CharleyBAZ** [comment]
Here is the ONE receiving address.  
![Screenshot_20220103-192912_Sef](https://user-images.githubusercontent.com/83322624/148001847-3e78d255-a298-4a3e-91c3-f321869fe611.jpg)

**Comment by polymorpher** [comment]
I will add support in the next version

**Comment by polymorpher** [comment]
Should work now with https://github.com/polymorpher/one-wallet/commit/d58922be836b8aa37d74b890b7b132c85a491862 . Use the QR code scanner on address bar
