### ISSUE TITLE
Want to restore my wallet, but says "This is a wallet, but is not a 1wallet address"

### ISSUE THREAD

**Issue by alpereira7** [polymorpher/one-wallet#234]
Hi, I would like to restore my wallet, but when I enter my address in the filed, I have a pop up that says "This is a wallet, but is not a 1wallet address".
I'm 100% sure this is my 1wallet address, I already restored in in the past.

**Comment by polymorpher** [comment]
Can you post the address here?

**Comment by polymorpher** [comment]
Any update? Closing for now
