### ISSUE TITLE
Cannot Create Wallet

### ISSUE THREAD

**Issue by ntindle** [polymorpher/one-wallet#242]
Connection Error: Error: Returned error: transaction underpriced

This blocks the creation of new wallets. I have tried multiple devices. There is no place to price the transaction.

**Comment by polymorpher** [comment]
Harmony network is down. Here is their live update: https://www.reddit.com/r/harmony_one/comments/s3n8r4/state_of_the_network_jan_13th_2022/

**Comment by polymorpher** [comment]
Seems to work now. Can you check?
