### ISSUE TITLE
Support for andOTP

### ISSUE THREAD

**Issue by freshprivacy** [polymorpher/one-wallet#249]
Right now it seems only google auth and aegis auth are supported. Any chance to add support for andOTP? To onboard the masses, support for more auth apps is crucial.

**Comment by polymorpher** [comment]
Is it not working? It says it is compatible with Google Authenticator. If it really is, then it should work

**Comment by freshprivacy** [comment]
I wasn't able to scan the qr code as it said it was an invalid qr code. I never had any issues with andOTP and use it as my default authenticator app.

**Comment by polymorpher** [comment]
I will show the QR code in a more compatible mode (such that authenticators other than Google's can still read it), and add a  toggle that will switch the QR code to something more tailored for Google Authenticator (in case some iOS users have trouble scanning it).

**Comment by polymorpher** [comment]
I can't find the app anymore on PlayStore. Can you let me know when it is back to the store again?
