### ISSUE TITLE
Add Sentry.io

### ISSUE THREAD

**Issue by givp** [polymorpher/one-wallet#26]

**Comment by polymorpher** [comment]
We still need to hook it up to all error handling routines and create different types of errors

**Comment by givp** [comment]
That's correct. But it will still catch JS errors and exceptions. If we want error handling for specific use cases, like inside try/catch blocks, we have to add those.

**Comment by givp** [comment]
I will start adding Sentry to all try/catch blocks like this:

```
try {
  aFunctionThatMightFail();
} catch (err) {
  Sentry.captureException(err);
}
```
