### ISSUE TITLE
wallets disappear after browsing history and data are cleared

### ISSUE THREAD

**Issue by cofinv** [polymorpher/one-wallet#266]
To test the new  1wallet, I have used the web browser to create 1wallet. 
utilized the google authenticator and all worked at the beginning. 
to test further I have sent 2one tokens to the address. Balance appeared immediately while using the new wallet. However after closing this web browser I lost my access to the wallet. I did originally bookmarked the wallet with the address but now I am sent to a general address. 
I can see this new address and balance on the blockchain explorer but I cannot see the wallet on the newly created 1wallet. 
The recovery is not working either. 
I am directed to https://1wallet.crazy.one/wallets
meanwhile my bookmarked address is supposed to be my own new wallet.

**Comment by cofinv** [comment]
Update
I did a few testing around.
With Google Authenticator, recovery is possible. Unfortunately, once user clears the browser history (even after recovery), user cannot reach to the wallet and need to recover again. 
This need fixing.

**Comment by polymorpher** [comment]
If you clear the browser history (and presumably any stored data as well), you can't really expect the browser not to clear all data stored by 1wallet.crazy.one as well.

You may find https://github.com/polymorpher/one-wallet/issues/255 helpful, which will be available in the next version. We are also considering to build a browser extension, which should address your issue (if you clear browser data a lot)
