### ISSUE TITLE
Transfers from 1wallet to KuCoin are not recognized and deposited into the exchange's accounts

### ISSUE THREAD

**Issue by Fonsi4** [polymorpher/one-wallet#267]
Hello all,

I've been trying to send ONEs to KuCoin ONEs wallet but it never arrived. Yesterday I sent 2000 ONEs and it got lost somewhere.

I was able to do it using the old Chrome wallet extension, but with the new 1Wallet my funds doesn't arrive.

Did someone experienced the same issue? Is there any way to recover my funds? 

This is the 1Wallet address =>  one1uc5j0sc4tmqndz94nzf3c0yy4fzn7lfvx7rym6

And this is the KuCoin Wallet => one19tw8xpmsthp6vgryydwktrfgng2s2thz5r87qr

And there the THash where you can see the transaction=> 

0xa1be8c4869adf2eb7596c3f90020d5da85a6c9ab26c4d865d08aed4fb0f9505e

If we don't support KuCoin yet, I think users should know, so they don't lost their funds.

**Comment by polymorpher** [comment]
KuCoin is an exchange, so I assume KuCoin wallet is referring to their custodial "wallets" i.e. your account in the exchange. There is a warning on the screen where you send funds, saying please don't send funds to exchange accounts (until they implement proper mechanisms to accept fund transfer from smart contracts). I have been thinking of ways to work around this issue but haven't come up with a satisfactory solution.

Have you checked if their customer support can manually fix it?

**Comment by Fonsi4** [comment]
I did the same as I normally do with the old Chrome Extension. I'm trying to contact with KuCoin support, but still no answer from their side.

I think the warning message could be more clear... I didn't understood it in this way till now, reading your comments... In any case, I'll try to contact with KuCoin.

**Comment by polymorpher** [comment]
Okay, I will improve the warning message

**Comment by polymorpher** [comment]
Updated the UI. I will make a new solution #293 to address this issue without Binance / KuCoin / crypto.com to modify their implementations

<img width="758" alt="image" src="https://user-images.githubusercontent.com/913871/163698361-f155561a-ecd8-44c5-9e89-14f8a53ba8ae.png">

**Comment by polymorpher** [comment]
(Done in https://github.com/polymorpher/one-wallet/commit/0cbcddbbaea98ddf028eebd54ae83e382b12d062)
