### ISSUE TITLE
MultiSig Withdrawal

### ISSUE THREAD

**Issue by 0xref** [polymorpher/one-wallet#291]
Withdrawal from a multisig wallet (wallet created via 1wallet infrastructure earlier) not working (used to work before)

Screenshots and tx hash below
<img width="512" alt="Screenshot 2022-04-15 at 06 50 02" src="https://user-images.githubusercontent.com/103708235/163503231-bc1a17f6-0cef-4c9e-9ed9-5f58040f7f3a.png">
<img width="595" alt="Screenshot 2022-04-15 at 06 50 31" src="https://user-images.githubusercontent.com/103708235/163503270-4a55fcd0-7e7c-45cf-a82e-160f1d17ebdf.png">
<img width="638" alt="Screenshot 2022-04-15 at 06 50 43" src="https://user-images.githubusercontent.com/103708235/163503282-02c6980e-67a8-4eb5-8ecb-1fdd7959a028.png">
<img width="795" alt="Screenshot 2022-04-15 at 06 51 27" src="https://user-images.githubusercontent.com/103708235/163503291-8056e949-4339-4773-957a-dc27f94b3bf4.png">
<img width="795" alt="Screenshot 2022-04-15 at 06 51 27" src="https://user-images.githubusercontent.com/103708235/163503297-d36e085b-1740-4a2e-a321-b05dc59c3472.png">
<img width="1213" alt="Screenshot 2022-04-15 at 06 51 46" src="https://user-images.githubusercontent.com/103708235/163503301-08092bf4-9295-43e1-ace8-93947c9ad137.png">
<img width="607" alt="Screenshot 2022-04-15 at 06 51 57" src="https://user-images.githubusercontent.com/103708235/163503307-43918484-cd8f-4028-9969-b7f363090031.png">

https://explorer.harmony.one/tx/0x23eea074e55e3df59edad02d633de2e490041b872bd5d186a378385d0c1fbf0b

Whereas incoming transfers to the contract works
<img width="1189" alt="Screenshot 2022-04-15 at 07 00 35" src="https://user-images.githubusercontent.com/103708235/163503624-457ab7a4-43d9-475a-a941-d20bb3a65cbc.png">

**Comment by polymorpher** [comment]
Can you post the addresses in text? OCR can't extract the text correctly

**Comment by polymorpher** [comment]
Also expand the details of the screen which you typed auth code

**Comment by 0xref** [comment]
Source address: 0xD74884cF6d42CCbEB0152a392489be59CFD77d93
Destination address: one164mn9x3ea6yfvqn46e7vuhtpfwgplxac33rsdg / 0xD577329A39Ee88960275D67ccE5d614b901f9bB8

TX Hash: 0x23eea074e55e3df59edad02d633de2e490041b872bd5d186a378385d0c1fbf0b

**Comment by 0xref** [comment]
> Also expand the details of the screen which you typed auth code

Will do a new transaction now to screenshot that

**Comment by polymorpher** [comment]
The call was made to a zero address, instead of your multisig address. I will check with https://github.com/hypnagonia who integrated the multisig

**Comment by 0xref** [comment]
When I zzom out on the browser, the state change on the UI is not visible. It just confirms the transaction

<img width="485" alt="Screenshot 2022-04-15 at 07 17 22" src="https://user-images.githubusercontent.com/103708235/163504890-917f52a4-8fde-4b38-84be-c3993cdcbff5.png">

**Comment by 0xref** [comment]
> The call was made to a zero address, instead of your multisig address. I will check with https://github.com/hypnagonia @hypnagonia who integrated the multisig

Thanks so much. Appreiciate it

**Comment by polymorpher** [comment]
click this?
<img width="127" alt="image" src="https://user-images.githubusercontent.com/913871/163504974-9f40c4c7-d5e4-4e35-9e85-c789bf980743.png">

**Comment by 0xref** [comment]
> click this? <img alt="image" width="127" src="https://user-images.githubusercontent.com/913871/163504974-9f40c4c7-d5e4-4e35-9e85-c789bf980743.png">
<img width="564" alt="Screenshot 2022-04-15 at 07 20 27" src="https://user-images.githubusercontent.com/103708235/163505156-af7568ab-6183-49c6-8d48-2a2e6da5dc4a.png">
<img width="562" alt="Screenshot 2022-04-15 at 07 20 20" src="https://user-images.githubusercontent.com/103708235/163505173-f695b5d4-a59b-492b-91b6-c5cc232a38b5.png">

**Comment by 0xref** [comment]
Zero address

**Comment by polymorpher** [comment]
I found the bug. Should be fixed in 5 min

**Comment by 0xref** [comment]
Thanks so much chief

**Comment by polymorpher** [comment]
did it work?

**Comment by 0xref** [comment]
> did it work?

Let me check and report back chief

**Comment by 0xref** [comment]
Tried in an incognito tab. 

Same issue so far.
<img width="559" alt="Screenshot 2022-04-15 at 08 55 13" src="https://user-images.githubusercontent.com/103708235/163513481-d76e5fe7-5208-44ee-8449-249e0cccc5bd.png">

**Comment by polymorpher** [comment]
just fixed it again and tested using one of my safes. It works now https://explorer.harmony.one/tx/0xfb23a4d1f52ac986f45719aa4a48340f3aef6806f0351344fc0010db19c5c179?activeTab=2

**Comment by 0xref** [comment]
Thanks, it works now.

**Comment by polymorpher** [comment]
Fixed by https://github.com/polymorpher/one-wallet/commit/4b0ae7f59ecebd2b7587f56c7962df332071ed96
