### ISSUE TITLE
Improve accuracy of Number of Wallets and Balance on ONEWallet SideBar

### ISSUE THREAD

**Issue by johnwhitton** [polymorpher/one-wallet#307]
### Overview
One Wallet Provides visiblity to Number of Wallets and their Balances on the HomeScreen.
This information is inaccurate due to the way these stats are retrieved (at time of creating this issue the stats are hardcoded [here](https://github.com/harmony-one/explorer-v2-backend/blob/master/src/api/controllers/oneWalletMetrics.ts#L15))
This ticket is to improve the accuracy of these stats.
<img width="207" alt="1WalletStats" src="https://user-images.githubusercontent.com/1572027/165177355-fb88bab3-b2d7-47e2-beff-ac10029372c1.png">

### Expected Result
Wallets reflects the total number of 1Wallets for the network
Balances reflects the total balance of all 1Wallets for the network

### Actual Result
Only a subset are being reported due to the query logic used in [explorer-v2-backend](https://github.com/harmony-one/explorer-v2-backend/blob/master/src/api/controllers/oneWalletMetrics.ts)

### Logic Overview
**One Wallet Client src**
* [`routes.js`](https://github.com/polymorpher/one-wallet/blob/master/code/client/src/routes.js#L9) imports component SiderMenu
* components ->[`SiderMenu.jsx`](https://github.com/polymorpher/one-wallet/blob/master/code/client/src/components/SiderMenu.jsx#L30) which calls StatsInfo
* components->[`StatsInfo.jsx`](https://github.com/polymorpher/one-wallet/blob/master/code/client/src/components/StatsInfo.jsx#L23) calls `fetchGlobalStats`
* state->modules->cache->[`handleFetchGlobalStats`](https://github.com/polymorpher/one-wallet/blob/master/code/client/src/state/modules/cache/sagas.js#L15) calls lib api

**One Wallet lib**
* api->[`walletStats`](https://github.com/polymorpher/one-wallet/blob/master/code/lib/api/index.js#L203) which calls https://explorer-v2-api.hmny.io/v0/1wallet/metrics

**Harmony Explorer v2 Backend API**: Currently the values are Hardcoded
* src->api->rest->[`server.ts`](https://github.com/harmony-one/explorer-v2-backend/blob/master/src/api/rest/server.ts#L21) imports `oneWalletMetricsRouter`
* src->api->rest->routes->[`oneWalletMetrics`](https://github.com/harmony-one/explorer-v2-backend/blob/master/src/api/rest/routes/oneWalletMetrics.ts#L10) which uses the controller 
* src->api->controllers->[`oneWalletMetrics`](https://github.com/harmony-one/explorer-v2-backend/blob/master/src/api/controllers/oneWalletMetrics.ts) returns hardcoded values but has sample code to call `oneWalletGetBalances` using `stores[0].oneWalletMetrics.getMetrics`

**Harmony Explorer Storage and Block Indexer and store**: Work has been done in storing the following
* src -> indexer -> indexer -> metrics -> [`oneWallet.ts`](https://github.com/harmony-one/explorer-v2-backend/blob/master/src/indexer/indexer/metrics/oneWallet.ts) calls `getAddressesToUpdateCount`
* src -> store -> postgres -> [OneWalletMetrics.ts](https://github.com/harmony-one/explorer-v2-backend/blob/master/src/store/postgres/OneWalletMetrics.ts) populates the table `onewallet_owners`
* src-> indexer -> indexer -> [`blockIndexer.ts`](https://github.com/harmony-one/explorer-v2-backend/blob/master/src/indexer/indexer/BlockIndexer.ts#L225) has logic to `addOneWalletOwners` using hardcoded addresses

### Proposed Solution
- [ ] Update OneWallet Client to retrieve values based on Network
- [ ] Remove Hardcoding of values in Harmony Explorer BackEnd
- [ ] Review Explorer Indexing and Storage logic 
  - [ ] Removal of hardcoded addresses
  - [ ] ensure support for multiple relayers
- [ ] Modify [Factory.sol](https://github.com/polymorpher/one-wallet/blob/master/code/contracts/ONEWallet.sol) and [FactoryHelper.sol](https://github.com/polymorpher/one-wallet/blob/master/code/contracts/FactoryHelper.sol#L25) deploy functions to maintain a `totalDeployedCount` and optionally a `WalletsDeployed` array.

[Here](https://github.com/harmony-one/explorer-v2-backend/pull/56) is the latest relevant commit for Harmony Explorer v2 Backend.
Which has this logic overview
```
1. check for 1wallet create when parsing block, write owner address to onewallet_owners table
2. once a day update balances and write total balance and owners count to onewallet_metrics table
3. read onewallet_metrics table last row on user requests to GET /v0/1wallet/metrics
Added new env variable INDEXER_ONEWALLET_IS_ENABLED
```

[Here](https://gist.github.com/johnwhitton/032294a16c77705294d34ea16f908432) are sample relayer and client testing deploy instructions

### Development Notes
This development is actively being worked on under the [stats branch](https://github.com/polymorpher/one-wallet/blob/stats/code/scripts/1wallets.js) 
The original (outdated approach is under https://github.com/polymorpher/one-wallet/pull/312

Latest Run retrieved using `1623217821095 is June 9th 2021 (just before wallets were created)`
for these relayers
`RELAYER_ADDRESSES='0xC8cD0C9Ca68b853F73917c36E9276770A8D8E4E0,0xfBe4dAdBbDB04Bf3CAbA788D9a7eb23e55313b1F,0xE0b00c60B17cB7987aD79F04Efd7e2572C4a6100,0xe76433Fe7261bDe3e0bbb18F12fE01d0D424E9cD,0xbbf2950F6Bf37928b83AB6d0D183fE6302238AC5,0xc292a5cf79b4942E489f74Ce9997A726789Cd5ED,0xe4f9c8318E6861e38bF65Ff494BABD5D3a4573a8,0xe60Ba21dbee59E4BCA4489E049313CC4603aeA17,0xE55201A6c90c75AC3d6aB8855E749D00807E26a4,0x1b494Fd8Fec1094f4515d5793DbCD70a457e88Ed,0xf8440BCbCFDb18564f3674DCF04EdEEe42bb747d'`
gave
```
writing refreshed stats {
  totalBalance: '31795000000000000000000',
  totalAddresses: 6349,
  lastBalanceRefresh: 1651193604308,
  lastScanTime: 1651193377616
}
```

### Outstanding Development Items
- [ ] Not all wallets are being extracted see [this example](https://explorer.harmony.one/address/0xdc9d1024241e488848250340770c2b97452c720d)
- [ ] Should review wallets that have been upgraded and see that they are not counted twice the above was upgraded 
- [ ] Need to clarify hexTime and hexBalance length (uint4 was failing so have made them both uint32
- [ ] fs.cp has been replaced with fs.copyFile but `fsConstants.COPYFILE_FICLONE_FORCE` is not working

### Original (outdated) approach)
**Sample Data**

* Relayer 0: one1erxse89x3wzn7uu30smwjfm8wz5d3e8quuvkgq = 0xc8cd0c9ca68b853f73917c36e9276770a8d8e4e0
* Relayer1: one1uzcqcc930jmes7khnuzwl4lz2uky5cgq78az79 = 0xe0b00c60b17cb7987ad79f04efd7e2572c4a6100
* OneWallet Deployed: one1ryky5n7uvps9n9aw7a3wfw65psz6480smh9nrd = 0x192c4a4fdc60605997aef762e4bb540c05aa9df0
* Deployed bytecode starts with : 0x60806040
* Event ONEWalletDeploySuccess: 0xbbfe2306f6111c06403cdf36cf7df46751a594b54d6da11bcca906ad8c9a711f

**Sample Command**
Running specifying date: `T0=2022/01/01 node 1wallets.js`

**Sample Files**
`totalsControl.json`: holds control data for the extract e.g.
```
{"controlInformation": [
    {"relayer": "0xc8cd0c9ca68b853f73917c36e9276770a8d8e4e0", "refreshWallets": true, "refreshBalances": true, "lastExtractTime": "2022-01-01T01:00:16-08:00", "walletCount": 0, "totalBalance": 0 },
    {"relayer": "0xe0b00c60b17cb7987ad79f04efd7e2572c4a6100", "refreshWallets": true, "refreshBalances": true, "lastExtractTime": "2022-01-01T01:00:16-08:00", "walletCount": 0, "totalBalance": 0 }
]
}
```

`totals.json`: holds the totals we are looking for e.g.
```
{ "walletCount" : 0, "totalBalance" : 0 }
```

`relayer_0xc8cd0c9ca68b853f73917c36e9276770a8d8e4e0.json` one file per relayer holds wallet information e.g.
```
{"wallets": [
    {"walletAddress":"0x3a44573abf3a1e246ab881eb8eaa89da29f4d5ac", "creationTime": "2022-01-01T01:00:16-08:00", "lastExtractTime": "2022-01-01T01:00:16-08:00", "balance": 0}
]
}
```

**Comment by polymorpher** [comment]
I suggest just extending the script in https://github.com/polymorpher/one-wallet/blob/master/code/scripts/1wallets.js, account for multiple relayer accounts and additional methods (f31e87d9) or events (0xbbfe2306f6111c06403cdf36cf7df46751a594b54d6da11bcca906ad8c9a711f). It can be done in a quite simple way, and without any reliance on explorer

**Comment by johnwhitton** [comment]
This is being worked on under this PR. https://github.com/polymorpher/one-wallet/pull/312

**Comment by polymorpher** [comment]
Fixed in https://github.com/polymorpher/one-wallet/pull/313
