### ISSUE TITLE
Can't request contract call

### ISSUE THREAD

**Issue by ArtemKolodko** [polymorpher/one-wallet#324]
**Description**
User can't call contract using 1wallet, "Next" button is disabled

**Live demo to reproduce: click link**
[https://1wallet.crazy.one/auth/call?caller=Harmony+MultiSig](https://1wallet.crazy.one/auth/call?caller=Harmony+MultiSig&callback=aHR0cHM6Ly9tdWx0aXNpZy5oYXJtb255Lm9uZS9vbmUtd2FsbGV0LWlmcmFtZS1jYWxsYmFjaw%3D%3D&calldata=eyJoZXgiOiIweDE2ODhmMGI5MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMzczNmFjODQwMDc1MWJmMDdjNmEyZTRkYjNmNGYzZDlkNDIyYWJiMjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwNjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDE4MjM0ZTljZjVlMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDE2NGI2M2U4MDBkMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDE0MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGM1ZDY1NGJjZTEyMjAyNDFmY2UxZjBmMWQ2YjllMDRmNzUxNzU0NTIwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwYWE4NDYxNjczNGU2MzkxOGZmYmZhMTBiNjBhODRlMWMxZjhiYjliZTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCJ9&dest=0x4f9b1def3a0f6747bf8c870a27d3decdf029100e&from=0xaa84616734e63918ffbfa10b60a84e1c1f8bb9be)

**Steps to reproduce (Multisig)**
1) Go to [https://multisig.harmony.one/](https://multisig.harmony.one/)
2) Connect 1wallet (top right corner)
3) Click "Create new safe", enter any name
4) Click "Start", "Review", "Submit"

<img width="1499" alt="Screen Shot 2022-07-25 at 12 38 58 PM" src="https://user-images.githubusercontent.com/8803471/180769660-0dcc1442-eacd-4142-bc9f-9c871a1748b0.png">

You can't request call and create a new multisig safe.

It seems that `(selectedAddress?.value) === false` on [this line](https://github.com/polymorpher/one-wallet/blob/master/code/client/src/integration/RequestCall.jsx#L153) and the button remains disabled

**Comment by polymorpher** [comment]
Sorry for the delay - I will take a look on Friday and get back to you

**Comment by polymorpher** [comment]
This is fixed. Sorry about the issue
