### ISSUE TITLE
ONE tokens did not arrive to 1wallet

### ISSUE THREAD

**Issue by Ancient666** [polymorpher/one-wallet#328]
I have made a swap from BNB to ONE at simpleswap, the swap was succesfull but ONE tokens never arrived to my 1wallet wallet, at history it shows "External Payment Received" and inmediatly "[Transaction Reverted]"

Here are the transactions: https://explorer.harmony.one/address/0xfF65B4fCb760B5E365cAbfd8940aDD23B01af968

Any way of solve this: Thanks in advance.

**Comment by polymorpher** [comment]
They (Kucoin) are trying to send the money with only 21000 gas (bare minimum for most basic transfer). They should have used some gas-estimation API or just used some value slightly higher than 21000. Can you contact them and ask them to fix it? You can show them this thread, and the transaction. The sender of the transaction is a centralized exchange so there is little I can do.

**Comment by Ancient666** [comment]
Thanks for the info. I'll try to contact them ;)

**Comment by Ancient666** [comment]
I am on coversation with KuCoin staff, they are working on it checking everything is ok... let's wait then

**Comment by Ancient666** [comment]
Problem solved with simpleswap staff =)
