### ISSUE TITLE
Emergency!! About to lose all funds in wallet due to expiration on an older version wallet.

### ISSUE THREAD

**Issue by Thorsr20** [polymorpher/one-wallet#333]
Good Morning. I had an issue #182 that was never resolved. Basically all my funds were stuck in an old wallet after upgrade because my recovery address was a Binance wallet and any funds sent from that wallet would just show Binances main wallet and not my own which wouldn't allow my funds to transfer to the upgraded wallet. So I've been stuck moving 1000 one at a time and do not have it all moved yet. I thought my old wallet would renew with my upgraded wallet but apparently that's not the case and now I have one day to figure out what to do or the rest of my one will be sent to my Binance address which we know will not work. What  are my options?

**Comment by polymorpher** [comment]
You can still control the old wallet after it is expired. How much is left there?

**Comment by Thorsr20** [comment]
122000

**Comment by Thorsr20** [comment]
So I'll still be able to send one to the new wallet each day? Right now it says I'll only be able to transfer it to the recovery but maybe it's different for old wallets that are tied to upgraded wallets?

**Comment by polymorpher** [comment]
Yes, old wallets can be controlled by their successors indefinitely
