### ISSUE TITLE
TRANSFER | Account Balance not Updated

### ISSUE THREAD

**Issue by AndyBoWu** [polymorpher/one-wallet#34]
Original ticket: https://github.com/harmony-one/chrome-extension-wallet/issues/102

**Comment by polymorpher** [comment]
Based on your description, the funds are deposited in the (contract) address but the balance in the explorer is not updated. It seems to be an issue with the explorer, which I can't do anything about. Can you ask them to reopen the original ticket and transfer it to an appropriate place where the explorer is developed?

Did you see correct balance on ONE Wallet UI?

**Comment by polymorpher** [comment]
Closed for now. Let me know if the one wallet UI is showing incorrect balance.
