### ISSUE TITLE
PRODUCT | Please Clearly Stated Which Authenticator Should be Used

### ISSUE THREAD

**Issue by AndyBoWu** [polymorpher/one-wallet#35]
Original ticket: https://github.com/harmony-one/chrome-extension-wallet/issues/103

**Comment by polymorpher** [comment]
Yes, I will fix it today

**Comment by polymorpher** [comment]
Fixed in https://github.com/polymorpher/one-wallet/commit/3bbc69ab6540df2d6c0b9c36eb16420ba7cb53fb
