### ISSUE TITLE
Failed to commit : network error on any transaction I try to make

### ISSUE THREAD

**Issue by quillboar2** [polymorpher/one-wallet#360]
Hello,
since several weeks, I have the error message Failed to commit : network error on any transaction I try to make on my 1wallet (stake, claim, send etc.).

When connecting, it tells me my wallet will expire in 1 month, but I click on "Later" , so the issue is not bad autentificator code.
I still have access to old authentificator and can still generate codes to prove I'm the owner of the wallet.

My wallet address is one15lp20k6ge2krv2pa4qtpsrphz6e2ajlu2nadg5.

Is there a way to do something with this wallet ?
Thanks and regards.

**Comment by quillboar2** [comment]
someone has a hint ? My wallet expires in less than 1 month and I have no way to make any operation with the funds.

**Comment by polymorpher** [comment]
Can you try again? We fixed the issue in https://github.com/polymorpher/one-wallet/issues/361
