### ISSUE TITLE
Network errors - cannot do anything?

### ISSUE THREAD

**Issue by mmatusevici1** [polymorpher/one-wallet#361]
since 4 or 5 months ago, I have been getting the error message "network error" on any action I try to make on my 1wallet (stake, claim, even create a new wallet).

Also, I really need help to undelegate my stake from 1wallet. I staked on staking.harmony.one and whenever I am trying to undelegate via staking.harmony.one,, it is asking to use either Ledger Nano or Harmony Browser extension. However, I delegated using 1wallet that uses Google Aithenticator and there is no such option.. if I am trying to press "Undelegate" on 1wallet interface,  I am getting a message: "Cannot find pre-computed proofs for this wallet. Storage might be corrupted. Please restore the wallet from Google authenticator". 

Another issue is that my 1wallet will expire in 11 days, and I cannot restore it because I am getting a message: "Local state verification failed" and "Network error". It means that my staked ONE will be staked forever because I will lose access to the wallet. 

Could somebody please help me as I am getting really desperate and I feel like I am out of options as there is no seed phrase here with 1wallet as it is relying on Google Authenticator and therefore I cannot use another wallet interface to try undelegate.
P.s. I have ONE in my wallet for gas.

**Comment by polymorpher** [comment]
Can you try again? We had a HTTPS certificate issue. Sorry about that.

**Comment by quillboar2** [comment]
now, the 1wallet is not accessible at all at this address : https://1wallet.crazy.one/ 
did it change ?

**Comment by polymorpher** [comment]
It should work now

**Comment by polymorpher** [comment]
Please reopen if the issue continues
