### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by anykeyh** [polymorpher/one-wallet#84]
Hey ! Thanks for the great work ! 

I'm wondering under which License this project is released? I would like to use some features of your wallet into a project we are currently building with friends.

There is currently no licensing information for this project. I can't assume this is open source unless you specifically tell me it is.

Thanks in advance !

**Comment by polymorpher** [comment]
Thanks. The project and its components are licensed under Apache-2.0, with the exception of things under `/smartotp` which is licensed under ISC.

**Comment by anykeyh** [comment]
Thank you for your prompt answer, I appreciate it. Might worth add the info somewhere in the README. Do you want me to create PR for that?

**Comment by polymorpher** [comment]
Thanks - since it touches on legal languages and rights, it needs to me. I will do it later tonight.  Thanks for the reminder.

**Comment by polymorpher** [comment]
done
